name: Disparar Testes E2E

on:
  push:
    branches: [main]

jobs:
  trigger-tests:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ” Obter token secreto
        run: echo "Token recebido com sucesso"

      - name: ğŸš€ Disparar workflow no repositÃ³rio de testes
        env:
          GH_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/Sinognator/cypress-intermediario-estudos/actions/workflows/ci.yml/dispatches \
            -d "{\"ref\":\"main\", \"inputs\":{\"commit_mensagem\": \"${COMMIT_MSG}\"}}"
